# Generated by Django 2.2.6 on 2021-10-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomExtendedPeriodicTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.PeriodicTask')),
                ('task_type', models.CharField(blank=True, choices=[('Auto synchronization', 'auto-sync'), ('Email notification', 'email-notify')], max_length=100, null=True)),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
