# Generated by Django 2.2.6 on 2021-10-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_tasks_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customextendedperiodictask',
            name='task_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
